ansible_connection: httpapi
ansible_network_os: eos
ansible_user: admin
ansible_password: "admin"
ansible_become: yes
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
