---
mgmt_int: Management1
mgmt_vrf: Mgmt
mgmt_ip: 192.168.34.102/23
lo0_ip: 192.168.36.102/32
bgp:
  asn: 65000
  router_id: 192.168.36.102
  listen_range: 10.0.2.0/24
  listen_range_evpn: 192.168.36.0/24
  maximum_paths: 4
  redistribute: connected
  pg_list:
    - name: leaf
      vrf: default
      peers:
        - name: leaf1
          peer_ip: 10.0.2.1
        - name: leaf2
          peer_ip: 10.0.2.3
        - name: leaf3
          peer_ip: 10.0.2.5
l3_interfaces:
  - name: Ethernet1
    ip_add: 10.0.2.0/31
    desc: "Et1-leaf1:Et1"
  - name: Ethernet2
    ip_add: 10.0.2.2/31
    desc: "Et2-leaf2:Et1"
  - name: Ethernet3
    ip_add: 10.0.2.4/31
    desc: "Et3-leaf3:Et1"